eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost
    
    
microservice:
 
 payment-service:
    endpoints:
      endpoint:
        uri: http://Payment-Service/payment/pay
  catalog-service:
    endpoints:
      endpoint:
        uri: http://Catalog-SERVICE/Catalog/placeVendor
  order-service:
    endpoints:
      endpoint:
        uri: http://Order-Service/Order/placeOrder
